name: presion_arterial_gemini
description: "Aplicación para registro y seguimiento de presión arterial para adultos mayores."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI y Iconos
  cupertino_icons: ^1.0.8
  
  # Almacenamiento Local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Internacionalización
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  
  # Gestión de Estado
  provider: ^6.1.1
  
  # Notificaciones
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.1
  
  # Generación de PDF
  pdf: ^3.10.2
  printing: ^5.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Generación de código
  hive_generator: ^1.1.3
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  # Para iOS - Configuración de permisos de notificaciones
  # flutter_local_notifications requiere esta configuración en Info.plist